### ISSUE TITLE
[Feature Request] Tidy links too

### ISSUE THREAD

**Issue by huyz** [charliecm/obsidian-tidy-footnotes#4]
Say I have a table like this:

```markdown
| Device                                                                                                                                                       | Connector                 | Output Power                  |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------- | ----------------------------- |
| **USB PD (Extended Power Range)**                                                                                                                            | USB-C                     | 240W (5/9/15/20/28/35/48V 5A) |
| [Apple 140W USB-C Power Adapter](https://www.apple.com/shop/product/MLYU3AM/A/140w-usb-c-power-adapter)                                                      | USB-C (& MagSafe 3 cable) | 140W (28V 5A)                 |
```
The link makes the table very hard to edit since it's so wide.  It would be great if there were a way to tidy these up and convert the hyperlinks into footnotes too

**Comment by charliecm** [comment]
@huyz I think converting links in table to footnotes would be beyond the scope of this plugin because the goal is to re-index existing footnotes.

For your use case, you can consider using the [Footnote Shortcut](https://github.com/akaalias/obsidian-footnotes) plugin, so you can quickly add footnotes as you edit the table, jump to footnote definition, and then back using the same keyboard shortcut.
